public class Main {
    public static void main(String[] args) {
        System.out.println("Привет мир!");
        System.out.println("Hello World!");
        int i = 1000000;
        System.out.println("значение переменой " + " i " + "с типом " + "int " + "равно " + i );
        byte b = 12;
        System.out.println("значение переменой" + " b" + " с типом" + " dyte " +  "равно" + b );
        short s = 32767;
        System.out.println("значение переменой " + "s " + "с типом " + "short " + "равно "+ s);
        long l = 923372036854775806L;
        System.out.println("значение переменой "+ "l" + "с типом " + "long " + "равно "+ l );
        float f = -1.01f;
        System.out.println("значение переменой " + "f " + "с типом "+ "f " + "равно" + f );
        double d = 1.1111111;
        System.out.println("значениепеременой "+ "d "+ "с типом " + "d " + "равно "+ d );
        float fd = 27.12f;
        System.out.println(fd);
        long lk = 987678965549l;
        System.out.println(lk);
        double ds = 2.786;
        System.out.println(ds);
        short sa = 569;
        System.out.println(sa);
        int in = -159;
        System.out.println(in);
        int nt = 27897;
        System.out.println(nt);
        byte bv = 67;
        System.out.println(bv);
        byte lp = 23;
        byte ac = 27;
        byte ea = 30;
        int numberStudents = lp + ac + ea ;
        int SheetsPaper = 480;
        System.out.println("на каждого ученика рассчитано " + (SheetsPaper / numberStudents) + " листов бумаги");
        short bottle2 = 16;
        int oneMinute = bottle2 / 2;
        System.out.println(oneMinute);
        short minutes20 = 20;
        int day =  60 * 24;
        System.out.println(day);
        int day3 = day * 3;
        System.out.println(day3);
        int month = day * 30;
        System.out.println(month);
        int bottle20 = bottle2 * 10;
        System.out.println("за " + minutes20 + " машина производит " + (oneMinute * minutes20) + " бутылок");
        System.out.println("за " + day + " машина производит " + (day * oneMinute) + " бутылок ");
        System.out.println("за " + day3 + " машина производит " + (day3 * oneMinute) + " бутылок");
        System.out.println("за " + month + " машина производит " + (month * oneMinute) + " бутылок");
        int totalPaint = 120;
        int  white = 2;
        int brown = 4;
        int oneClass = white +brown;
        System.out.println(oneClass);
        int totalClasses = totalPaint / oneClass;
        System.out.println(totalClasses);
        int totalWhite = totalClasses * white;
        System.out.println(totalWhite);
        int totalBrown = totalClasses * brown;
        System.out.println(totalBrown);
        System.out.println("В школе,где " + totalClasses + " классов ,нужно "  + totalWhite + " банок белой краски и " + totalBrown + " банок коричневой краски ");
        int bananas = 5*80;
        System.out.println(bananas);
        int milk = 105*2;
        System.out.println(milk);
        int iceCream = 100 *2;
        System.out.println(iceCream);
        int eggs = 4*70;
        System.out.println(eggs);
        int grams = bananas + milk + eggs;
        System.out.println(grams );
        float kilogram = grams / 100f;
         System.out.println(kilogram);
         int totalKilogram = 7 *1000;
         System.out.println(totalKilogram);
         int day1 = 250;
         System.out.println("спортсен похудеет на 7 кг за " + (totalKilogram / day1));
         int day2 = 500;
         System.out.println("спортсмен похудеет на 7 кг за " + ( totalKilogram / day2));
         int averageDay = 28+14;
         System.out.println(averageDay);
         System.out.println( "в среднем потребуется дней для достижения результата " + (averageDay / 2) );
         int m = 67760;
         int m1 = (m/100) *10;
         System.out.println(m1);
         int m2 = m + m1;
         System.out.println(m2);
         System.out.println("маша теперь получает " + m2 + " рублей.Годовой доход вырос на " + m1 + " рублей");
         int d3 = 83690;
         int d1 = (d3 /100) *10;
         System.out.println(d1);
         int d2 = d3 + d1;
         System.out.println(d2);
         System.out.println("денис теперь получает " + d2 + " рублей .Годовой доход вырос нв " + d1 + " рублей");
         int k = 76230;
         int k1 = (k /100) *10;
         System.out.println(k1);
         int k2 = k + k1;
         System.out.println(k2);
         System.out.println("кристина теперь получает " + k2 + " рублей .Годовой доход вырос на"  +k1 +" рублей");
    }
}