public class Main {
    public static void main(String[] args) {
        System.out.println("Привет мир!");
        System.out.println("Hello World!");
        int i = 1000000;
        System.out.println("значение переменой " + " i " + "с типом " + "int " + "равно " + i );
        byte b = 12;
        System.out.println("значение переменой" + " b" + " с типом" + " dyte " +  "равно" + b );
        short s = 32767;
        System.out.println("значение переменой " + "s " + "с типом " + "short " + "равно "+ s);
        long l = 923372036854775806L;
        System.out.println("значение переменой "+ "l" + "с типом " + "long " + "равно "+ l );
        float f = -1.01f;
        System.out.println("значение переменой " + "f " + "с типом "+ "f " + "равно" + f );
        double d = 1.1111111;
        System.out.println("значениепеременой "+ "d "+ "с типом " + "d " + "равно "+ d );
        float fd = 27.12f;
        System.out.println(fd);
        long lk = 987678965549l;
        System.out.println(lk);
        double ds = 2.786;
        System.out.println(ds);
        short sa = 569;
        System.out.println(sa);
        int in = -159;
        System.out.println(in);
        int nt = 27897;
        System.out.println(nt);
        byte bv = 67;
        System.out.println(bv);
        byte lp = 23;
        byte ac = 27;
        byte ea = 30;
        int NumberStudents = lp + ac + ea ;
        int SheetsPaper = 480;
        System.out.println("на каждого ученика рассчитано " + (SheetsPaper / NumberStudents) + " листов бумаги");
        short Bottle2 = 16;
        int OneMinute = Bottle2 / 2;
        System.out.println(OneMinute);
        short minutes20 = 20;
        int day =  60 * 24;
        System.out.println(day);
        int day3 = day * 3;
        System.out.println(day3);
        int Month = day * 30;
        System.out.println(Month);
        int Bottle20 = Bottle2 * 10;
        System.out.println("за " + minutes20 + " машина производит " + (OneMinute * minutes20) + " бутылок");
        System.out.println("за " + day + " машина производит " + (day * OneMinute) + " бутылок ");
        System.out.println("за " + day3 + " машина производит " + (day3 * OneMinute) + " бутылок");
        System.out.println("за " + Month + " машина производит " + (Month * OneMinute) + " бутылок");
        int TotalPaint = 120;
        int  White = 2;
        int Brown = 4;
        int OneClass = White +Brown;
        System.out.println(OneClass);
        int TotalClasses = TotalPaint / OneClass;
        System.out.println(TotalClasses);
        int TotalWhite = TotalClasses * White;
        System.out.println(TotalWhite);
        int TotalBrown = TotalClasses * Brown;
        System.out.println(TotalBrown);
        System.out.println("В школе,где " + TotalClasses + " классов ,нужно "  + TotalWhite + " банок белой краски и " + TotalBrown + " банок коричневой краски ");
        int Bananas = 5*80;
        System.out.println(Bananas);
        int Milk = 105*2;
        System.out.println(Milk);
        int IceCream = 100 *2;
        System.out.println(IceCream);
        int Eggs = 4*70;
        System.out.println(Eggs);
        int Grams = Bananas + Milk + Eggs;
        System.out.println(Grams );
        float Kilogram = Grams / 100f;
         System.out.println(Kilogram);
         int TotalKilogram = 7 *1000;
         System.out.println(TotalKilogram);
         int Day1 = 250;
         System.out.println("спортсен похудеет на 7 кг за " + (TotalKilogram / Day1));
         int Day2 = 500;
         System.out.println("спортсмен похудеет на 7 кг за " + ( TotalKilogram / Day2));
         int AverageDay = 28+14;
         System.out.println(AverageDay);
         System.out.println( "в среднем потребуется дней для достижения результата " + (AverageDay / 2) );
         int M = 67760;
         int M1 = (M /100) *10;
         System.out.println(M1);
         int M2 = M + M1;
         System.out.println(M2);
         System.out.println("Мфша теперь получает " + M2 + " рублей.Годовой доход вырос на " + M1 + " рублей");
         int D = 83690;
         int D1 = (D /100) *10;
         System.out.println(D1);
         int D2 = D + D1;
         System.out.println(D2);
         System.out.println("денис теперь получает " + D2 + " рублей .Годовой доход вырос нв " + D1 + " рублей");
         int K = 76230;
         int K1 = (K /100) *10;
         System.out.println(K1);
         int K2 = K + K1;
         System.out.println(K2);
         System.out.println("кристина теперь получает " + K2 + " рублей .Годовой доход вырос на"  +K1 +" рублей");
    }
}